(() => {
  const grid=document.getElementById('classGrid'), filter=document.getElementById('venueFilter'), dialog=document.getElementById('bookingDialog'), form=document.getElementById('bookingForm');
  let classes=[];
  const money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(n);
  const dateFmt=s=>new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s));
  function render(){const v=filter.value;const rows=classes.filter(c=>v==='all'||c.venue===v);grid.innerHTML=rows.length?rows.map(c=>`<article class="class-card"><div class="class-date"><span>${new Date(c.starts_at).toLocaleDateString('en-GB',{month:'short'}).toUpperCase()}</span><strong>${new Date(c.starts_at).getDate()}</strong></div><div class="class-info"><p class="class-venue">${c.venue}</p><h3>${c.title}</h3><p>${dateFmt(c.starts_at)}</p><p>${c.location}</p><div class="class-footer"><span><b>${money(c.price)}</b> per person</span><span class="spaces ${c.spaces_remaining<5?'low':''}">${c.spaces_remaining} spaces left</span></div></div><button class="button book-class" data-id="${c.id}" ${c.spaces_remaining<1?'disabled':''}>${c.spaces_remaining<1?'Sold out':'Book now'}</button></article>`).join(''):'<p class="booking-empty">No classes match this filter.</p>';}
  async function load(){try{const r=await fetch('/api/classes',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error();classes=await r.json();}catch(e){classes=[
    {id:'ecc-2026-08-07',title:'Beginner Line Dancing',venue:'Edgbaston Community Centre',location:'Birmingham',starts_at:'2026-08-07T19:30:00+01:00',price:6,spaces_remaining:20},
    {id:'low-2026-08-14',title:'Class & Social Dancing',venue:'Low Places',location:'Birmingham',starts_at:'2026-08-14T19:15:00+01:00',price:6,spaces_remaining:24},
    {id:'ecc-2026-08-21',title:'Beginner Line Dancing',venue:'Edgbaston Community Centre',location:'Birmingham',starts_at:'2026-08-21T19:30:00+01:00',price:6,spaces_remaining:20},
    {id:'special-2026-08-26',title:'Boot Scootin’ Special',venue:'Special Event',location:'Birmingham',starts_at:'2026-08-26T19:30:00+01:00',price:6,spaces_remaining:25}
  ];document.getElementById('bookingStatus').hidden=false;document.getElementById('bookingStatus').textContent='Secure booking backend is in setup mode. No real booking will be taken until payment configuration is complete.';}
    [...new Set(classes.map(c=>c.venue))].forEach(v=>filter.insertAdjacentHTML('beforeend',`<option>${v}</option>`));render();}
  grid.addEventListener('click',e=>{const b=e.target.closest('.book-class');if(!b)return;const c=classes.find(x=>x.id===b.dataset.id);document.getElementById('classId').value=c.id;document.getElementById('selectedClassName').textContent=c.title;document.getElementById('selectedClassMeta').textContent=`${dateFmt(c.starts_at)} · ${c.venue} · ${money(c.price)} per person`;dialog.showModal();});
  document.getElementById('closeBooking').onclick=()=>dialog.close();filter.onchange=render;
  form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const msg=document.getElementById('formMessage'),btn=form.querySelector('button[type=submit]');btn.disabled=true;msg.textContent='Creating your secure checkout…';const data=Object.fromEntries(new FormData(form));try{const r=await fetch('/api/create-checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const out=await r.json();if(!r.ok)throw new Error(out.error||'Booking could not be created.');if(!out.checkout_url)throw new Error('Secure payment is not configured yet.');location.href=out.checkout_url;}catch(err){msg.textContent=err.message;}finally{btn.disabled=false;}});
  load();
})();