(() => {
  const state={classes:[],bookings:null,media:[],health:null};
  const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(p)||0)/100);
  const fmt=s=>s?new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s)):'—';
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const panels=[...document.querySelectorAll('[data-view-panel]')],nav=[...document.querySelectorAll('.ranch-nav button:not([disabled])')];
  function show(view){panels.forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===view));nav.forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('ranchTitle').textContent=nav.find(b=>b.dataset.view===view)?.textContent.trim()||'Boot Scootin’ HQ';document.getElementById('ranchSidebar').classList.remove('open');}
  nav.forEach(b=>b.onclick=()=>show(b.dataset.view));
  document.getElementById('ranchMenuButton').onclick=()=>document.getElementById('ranchSidebar').classList.toggle('open');


  const healthLabels={
    website:['Website','Public site and HQ frontend are responding.'],
    database:['Database','Cloudflare D1 class and booking storage.'],
    media:['Media storage','Cloudflare R2 photos, videos and PDFs.'],
    payments:['Payments','SumUp connection and operating mode.'],
    email:['Email confirmations','Transactional email provider.'],
    access:['Admin protection','Cloudflare Access identity header.'],
    backups:['Backups','Pilot backup and export readiness.']
  };
  function healthCard(key,item){const [title,desc]=healthLabels[key]||[key,''];const status=item?.status||'unknown';return `<article class="hq-health-card ${esc(status)}"><span class="health-dot ${esc(status)}"></span><div><strong>${esc(title)}</strong><small>${esc(item?.message||desc)}</small></div><b>${esc(status.replaceAll('_',' '))}</b></article>`;}
  function renderHealth(){const grid=document.getElementById('hqHealthGrid'),mini=document.getElementById('hqHealthMini'),h=state.health;if(!h)return;const keys=['website','access','database','media','payments','email','backups'];if(grid)grid.innerHTML=keys.map(k=>healthCard(k,h.services?.[k])).join('');const ready=keys.filter(k=>['ready','online','protected'].includes(h.services?.[k]?.status)).length;const attention=keys.length-ready;if(mini)mini.innerHTML=`<span class="health-dot ${attention?'attention':'ready'}"></span><strong>${ready} ready</strong><span> · ${attention} ${attention===1?'item needs':'items need'} attention</span><a href="#" data-open-health>View details</a>`;document.querySelectorAll('[data-open-health]').forEach(a=>a.onclick=e=>{e.preventDefault();show('health');});}
  async function loadHealth(){const grid=document.getElementById('hqHealthGrid'),mini=document.getElementById('hqHealthMini');if(grid)grid.innerHTML='<article class="hq-health-card"><span class="health-dot checking"></span><div><strong>Checking services…</strong><small>Please wait.</small></div></article>';if(mini)mini.innerHTML='<span class="health-dot checking"></span> Checking your setup…';try{state.health=await jsonFetch('/api/admin/health?version=73',{cache:'no-store'});renderHealth();}catch(e){state.health={services:{website:{status:'online',message:'This page loaded successfully.'},access:{status:'attention',message:e.message},database:{status:'attention',message:'Could not run the protected health check.'},media:{status:'attention',message:'Could not run the protected health check.'},payments:{status:'setup',message:'Not connected to SumUp sandbox yet.'},email:{status:'setup',message:'Not connected yet.'},backups:{status:'setup',message:'Export and restore test not completed yet.'}}};renderHealth();}}

  async function jsonFetch(url,options){const r=await fetch(url,{headers:{Accept:'application/json','Content-Type':'application/json',...(options?.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'The Ranch backend is not configured yet.');return d;}
  async function loadClasses(){try{state.classes=await jsonFetch('/api/admin/classes');document.getElementById('ranchNotice').hidden=true;}catch(e){state.classes=[];document.getElementById('ranchNotice').hidden=false;document.getElementById('ranchNotice').textContent=e.message+' The dashboard is showing setup mode until Cloudflare D1 and Access are connected.';}renderClasses();renderOverview();}
  async function loadBookings(){const box=document.getElementById('ranchBookings');try{state.bookings=await jsonFetch('/api/admin/bookings');renderBookings();}catch(e){box.innerHTML=`<div class="ranch-empty"><strong>Bookings are not connected yet.</strong><p>${esc(e.message)}</p></div>`;}}
  async function loadMedia(){const box=document.getElementById('ranchMedia');if(!box)return;try{const data=await jsonFetch('/api/admin/media');state.media=data.items||[];document.getElementById('ranchMediaCount').textContent=state.media.length;renderMedia();}catch(e){state.media=[];document.getElementById('ranchMediaCount').textContent='—';box.innerHTML=`<div class="ranch-empty"><strong>Media storage is not connected yet.</strong><p>${esc(e.message)}</p></div>`;}}
  async function checkMediaBackend(){const box=document.getElementById('mediaBackendStatus');if(!box)return;box.className='hq-backend-status checking';box.innerHTML='<strong>Checking media connection…</strong><span>Checking HQ login and Cloudflare R2 storage.</span>';try{const r=await fetch('/api/admin/media-status?version=73',{cache:'no-store',headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));const checks=d.checks||{};const rows=Object.entries(checks).map(([k,v])=>`<li><b>${v.ready?'✓':'×'}</b><span><strong>${esc(k.replace(/([A-Z])/g,' $1'))}</strong> — ${esc(v.message||'')}</span></li>`).join('');box.className=`hq-backend-status ${d.ready?'ready':'error'}`;box.innerHTML=`<strong>${d.ready?'Media Manager is connected':'Media Manager needs setup'}</strong><span>${esc(d.error||'Uploads can now be stored securely in Cloudflare R2.')}</span><ul class="media-check-list">${rows}</ul>`;return d.ready;}catch(e){box.className='hq-backend-status error';box.innerHTML=`<strong>Connection check failed</strong><span>${esc(e.message)}</span>`;return false;}}
  function renderMedia(){const box=document.getElementById('ranchMedia');if(!box)return;box.innerHTML=state.media.length?state.media.map(m=>`<article class="ranch-media-item"><div class="ranch-media-preview">${m.media_type==='image'?`<img src="/media/${encodeURIComponent(m.storage_key)}" alt="">`:m.media_type==='video'?'<span>VIDEO</span>':m.media_type==='pdf'?'<span>PDF</span>':'<span>FILE</span>'}</div><div class="ranch-media-copy"><strong>${esc(m.title)}</strong><small>${esc(m.original_name)} · ${esc(m.placement||'library')}</small><code>/media/${esc(m.storage_key)}</code></div><div class="ranch-media-actions"><button data-copy-media="${esc(m.storage_key)}">Copy link</button><button data-delete-media="${esc(m.id)}">Delete</button></div></article>`).join(''):'<div class="ranch-empty">No media uploaded yet.</div>';}
  function renderOverview(){const open=state.classes.filter(c=>c.status==='open'&&new Date(c.starts_at)>=new Date());const sold=state.classes.reduce((n,c)=>n+Number(c.sold||0),0);const revenue=state.classes.reduce((n,c)=>n+(Number(c.sold||0)*Number(c.price_pence||0)),0);const stats=document.getElementById('ranchStats').children;stats[0].querySelector('strong').textContent=open.length;stats[1].querySelector('strong').textContent=sold;stats[2].querySelector('strong').textContent=money(revenue);const up=document.getElementById('ranchUpcoming');up.innerHTML=open.length?open.slice(0,5).map(c=>`<article><div><strong>${esc(c.title)}</strong><span>${fmt(c.starts_at)} · ${esc(c.venue)}</span></div><b>${Math.max(0,c.capacity-c.sold)} left</b></article>`).join(''):'<div class="ranch-empty">No upcoming classes yet. Add your first class.</div>';}
  function renderClasses(){const filter=document.getElementById('ranchClassFilter').value;let rows=[...state.classes];if(filter==='upcoming')rows=rows.filter(c=>new Date(c.starts_at)>=new Date()&&!['cancelled'].includes(c.status));else if(filter!=='all')rows=rows.filter(c=>c.status===filter);const box=document.getElementById('ranchClasses');box.innerHTML=rows.length?`<div class="ranch-table-head"><span>Class</span><span>Date</span><span>Capacity</span><span>Status</span><span></span></div>${rows.map(c=>`<article class="ranch-class-row"><div><strong>${esc(c.title)}</strong><small>${esc(c.venue)} · ${esc(c.location)}</small></div><span>${fmt(c.starts_at)}</span><span>${Number(c.sold||0)} / ${c.capacity}</span><span><i class="status-pill ${esc(c.status)}">${esc(c.status)}</i></span><div class="ranch-actions"><button data-edit="${esc(c.id)}">Edit</button><button data-delete="${esc(c.id)}">Delete</button></div></article>`).join('')}`:'<div class="ranch-empty">No classes in this view.</div>';}
  function renderBookings(){const d=state.bookings,box=document.getElementById('ranchBookings');const stats=document.getElementById('ranchStats')?.children;if(stats&&d?.stats){stats[1].querySelector('strong').textContent=d.stats.guests;}
    box.innerHTML=d?.classes?.length?d.classes.map(c=>`<section class="register"><h3>${esc(c.title)}</h3><p>${fmt(c.starts_at)} · ${esc(c.venue)}</p><div class="ranch-register-table"><table><thead><tr><th>Name</th><th>Email</th><th>Places</th><th>Reference</th></tr></thead><tbody>${c.bookings.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(b.email)}</td><td>${b.quantity}</td><td>${esc(b.reference)}</td></tr>`).join('')}</tbody></table></div></section>`).join(''):'<div class="ranch-empty">No paid bookings yet.</div>';}

  const dialog=document.getElementById('classDialog'),form=document.getElementById('classForm');
  const venueDefaults={
    'Edgbaston Community Centre':{capacity:20,location:'Edgbaston Community Centre, Birmingham'},
    'Low Places':{capacity:50,location:'Low Places, Birmingham'}
  };
  const venueSelect=document.getElementById('ranchVenue');
  venueSelect?.addEventListener('change',()=>{const d=venueDefaults[venueSelect.value];if(!d)return;document.getElementById('ranchCapacity').value=d.capacity;document.getElementById('ranchLocation').value=d.location;});
  function openClass(c){form.reset();if(c&&venueSelect&&!Array.from(venueSelect.options).some(o=>o.value===c.venue)){venueSelect.add(new Option(c.venue,c.venue));}document.getElementById('classDialogTitle').textContent=c?'Edit class':'Add a class';document.getElementById('ranchClassId').value=c?.id||'';if(c){for(const [k,v] of Object.entries(c)){const el=form.elements[k];if(!el)continue;if(k==='starts_at'||k==='ends_at')el.value=v?new Date(v).toISOString().slice(0,16):'';else if(k==='price_pence')form.elements.price.value=(v/100).toFixed(2);else el.value=v??'';}}dialog.showModal();}
  document.querySelectorAll('[data-open-class]').forEach(b=>b.onclick=()=>openClass());
  document.getElementById('closeClassDialog').onclick=()=>dialog.close();
  document.getElementById('ranchClasses').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openClass(state.classes.find(c=>c.id===edit.dataset.edit));if(del&&confirm('Delete this class? This cannot be undone.'))removeClass(del.dataset.delete);};
  async function removeClass(id){try{await jsonFetch('/api/admin/classes',{method:'DELETE',body:JSON.stringify({id})});await loadClasses();}catch(e){alert(e.message);}}
  form.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('classFormMessage');msg.textContent='Saving…';const data=Object.fromEntries(new FormData(form));data.capacity=Number(data.capacity);data.price_pence=Math.round(Number(data.price)*100);delete data.price;try{await jsonFetch('/api/admin/classes',{method:data.id?'PATCH':'POST',body:JSON.stringify(data)});dialog.close();await loadClasses();msg.textContent='';}catch(err){msg.textContent=err.message;}});
  document.getElementById('ranchClassFilter').onchange=renderClasses;
  document.getElementById('refreshRanch').onclick=loadClasses;
  document.getElementById('refreshBookings').onclick=loadBookings;
  document.getElementById('refreshMedia')?.addEventListener('click',loadMedia);
  document.getElementById('checkMediaBackend')?.addEventListener('click',checkMediaBackend);
  document.getElementById('refreshHealth')?.addEventListener('click',loadHealth);
  document.getElementById('refreshHealthSummary')?.addEventListener('click',loadHealth);
  document.getElementById('ranchMedia')?.addEventListener('click',async e=>{const copy=e.target.closest('[data-copy-media]'),del=e.target.closest('[data-delete-media]');if(copy){await navigator.clipboard.writeText(`${location.origin}/media/${copy.dataset.copyMedia}`);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy link',1200);}if(del&&confirm('Delete this media file? Any page using it will stop displaying it.')){try{await jsonFetch('/api/admin/media',{method:'DELETE',body:JSON.stringify({id:del.dataset.deleteMedia})});await loadMedia();}catch(err){alert(err.message);}}});
  document.getElementById('mediaUploadForm')?.addEventListener('submit',async e=>{e.preventDefault();const formEl=e.currentTarget,msg=document.getElementById('mediaUploadMessage'),button=formEl.querySelector('button[type="submit"]'),file=formEl.elements.file.files[0];msg.className='form-message';if(!file)return;if(file.size>80*1024*1024){msg.classList.add('error');msg.textContent='This file is larger than 80 MB. Please compress it before uploading.';return;}const ready=await checkMediaBackend();if(!ready){msg.classList.add('error');msg.textContent='Upload stopped safely. Complete the connection items shown above, then press Check connection.';return;}const data=new FormData(formEl);button.disabled=true;msg.textContent='Uploading securely… Please keep this page open.';try{const r=await fetch('/api/admin/media',{method:'POST',body:data,headers:{Accept:'application/json'}});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||'Upload failed.');formEl.reset();msg.classList.add('success');msg.textContent=`Upload complete. ${out.note||'The website placement will update automatically.'}`;await loadMedia();}catch(err){msg.classList.add('error');msg.textContent=err.message;}finally{button.disabled=false;}});
  loadClasses();loadBookings();loadMedia();loadHealth();checkMediaBackend();
})();
