(() => {
  const state={classes:[],bookings:null};
  const money=p=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format((Number(p)||0)/100);
  const fmt=s=>s?new Intl.DateTimeFormat('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s)):'—';
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const panels=[...document.querySelectorAll('[data-view-panel]')],nav=[...document.querySelectorAll('.ranch-nav button:not([disabled])')];
  function show(view){panels.forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===view));nav.forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('ranchTitle').textContent=nav.find(b=>b.dataset.view===view)?.textContent.trim()||'Boot Scootin’ Ranch';document.getElementById('ranchSidebar').classList.remove('open');}
  nav.forEach(b=>b.onclick=()=>show(b.dataset.view));
  document.getElementById('ranchMenuButton').onclick=()=>document.getElementById('ranchSidebar').classList.toggle('open');

  async function jsonFetch(url,options){const r=await fetch(url,{headers:{Accept:'application/json','Content-Type':'application/json',...(options?.headers||{})},...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'The Ranch backend is not configured yet.');return d;}
  async function loadClasses(){try{state.classes=await jsonFetch('/api/admin/classes');document.getElementById('ranchNotice').hidden=true;}catch(e){state.classes=[];document.getElementById('ranchNotice').hidden=false;document.getElementById('ranchNotice').textContent=e.message+' The dashboard is showing setup mode until Cloudflare D1 and Access are connected.';}renderClasses();renderOverview();}
  async function loadBookings(){const box=document.getElementById('ranchBookings');try{state.bookings=await jsonFetch('/api/admin/bookings');renderBookings();}catch(e){box.innerHTML=`<div class="ranch-empty"><strong>Bookings are not connected yet.</strong><p>${esc(e.message)}</p></div>`;}}
  function renderOverview(){const open=state.classes.filter(c=>c.status==='open'&&new Date(c.starts_at)>=new Date());const sold=state.classes.reduce((n,c)=>n+Number(c.sold||0),0);const revenue=state.classes.reduce((n,c)=>n+(Number(c.sold||0)*Number(c.price_pence||0)),0);const stats=document.getElementById('ranchStats').children;stats[0].querySelector('strong').textContent=open.length;stats[1].querySelector('strong').textContent=sold;stats[2].querySelector('strong').textContent=money(revenue);const up=document.getElementById('ranchUpcoming');up.innerHTML=open.length?open.slice(0,5).map(c=>`<article><div><strong>${esc(c.title)}</strong><span>${fmt(c.starts_at)} · ${esc(c.venue)}</span></div><b>${Math.max(0,c.capacity-c.sold)} left</b></article>`).join(''):'<div class="ranch-empty">No upcoming classes yet. Add your first class.</div>';}
  function renderClasses(){const filter=document.getElementById('ranchClassFilter').value;let rows=[...state.classes];if(filter==='upcoming')rows=rows.filter(c=>new Date(c.starts_at)>=new Date()&&!['cancelled'].includes(c.status));else if(filter!=='all')rows=rows.filter(c=>c.status===filter);const box=document.getElementById('ranchClasses');box.innerHTML=rows.length?`<div class="ranch-table-head"><span>Class</span><span>Date</span><span>Capacity</span><span>Status</span><span></span></div>${rows.map(c=>`<article class="ranch-class-row"><div><strong>${esc(c.title)}</strong><small>${esc(c.venue)} · ${esc(c.location)}</small></div><span>${fmt(c.starts_at)}</span><span>${Number(c.sold||0)} / ${c.capacity}</span><span><i class="status-pill ${esc(c.status)}">${esc(c.status)}</i></span><div class="ranch-actions"><button data-edit="${esc(c.id)}">Edit</button><button data-delete="${esc(c.id)}">Delete</button></div></article>`).join('')}`:'<div class="ranch-empty">No classes in this view.</div>';}
  function renderBookings(){const d=state.bookings,box=document.getElementById('ranchBookings');const stats=document.getElementById('ranchStats')?.children;if(stats&&d?.stats){stats[1].querySelector('strong').textContent=d.stats.guests;}
    box.innerHTML=d?.classes?.length?d.classes.map(c=>`<section class="register"><h3>${esc(c.title)}</h3><p>${fmt(c.starts_at)} · ${esc(c.venue)}</p><div class="ranch-register-table"><table><thead><tr><th>Name</th><th>Email</th><th>Places</th><th>Reference</th></tr></thead><tbody>${c.bookings.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(b.email)}</td><td>${b.quantity}</td><td>${esc(b.reference)}</td></tr>`).join('')}</tbody></table></div></section>`).join(''):'<div class="ranch-empty">No paid bookings yet.</div>';}

  const dialog=document.getElementById('classDialog'),form=document.getElementById('classForm');
  function openClass(c){form.reset();document.getElementById('classDialogTitle').textContent=c?'Edit class':'Add a class';document.getElementById('ranchClassId').value=c?.id||'';if(c){for(const [k,v] of Object.entries(c)){const el=form.elements[k];if(!el)continue;if(k==='starts_at'||k==='ends_at')el.value=v?new Date(v).toISOString().slice(0,16):'';else if(k==='price_pence')form.elements.price.value=(v/100).toFixed(2);else el.value=v??'';}}dialog.showModal();}
  document.querySelectorAll('[data-open-class]').forEach(b=>b.onclick=()=>openClass());
  document.getElementById('closeClassDialog').onclick=()=>dialog.close();
  document.getElementById('ranchClasses').onclick=e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(edit)openClass(state.classes.find(c=>c.id===edit.dataset.edit));if(del&&confirm('Delete this class? This cannot be undone.'))removeClass(del.dataset.delete);};
  async function removeClass(id){try{await jsonFetch('/api/admin/classes',{method:'DELETE',body:JSON.stringify({id})});await loadClasses();}catch(e){alert(e.message);}}
  form.addEventListener('submit',async e=>{e.preventDefault();const msg=document.getElementById('classFormMessage');msg.textContent='Saving…';const data=Object.fromEntries(new FormData(form));data.capacity=Number(data.capacity);data.price_pence=Math.round(Number(data.price)*100);delete data.price;try{await jsonFetch('/api/admin/classes',{method:data.id?'PATCH':'POST',body:JSON.stringify(data)});dialog.close();await loadClasses();msg.textContent='';}catch(err){msg.textContent=err.message;}});
  document.getElementById('ranchClassFilter').onchange=renderClasses;
  document.getElementById('refreshRanch').onclick=loadClasses;
  document.getElementById('refreshBookings').onclick=loadBookings;
  loadClasses();loadBookings();
})();
